services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest # Use the latest official MongoDB image
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    environment:
      MONGO_INITDB_DATABASE: songbook  # Set database name
      MONGO_INITDB_COLLECTION: songs  # Set collection name
    volumes:
      - mongodb-data:/app/db # Persist MongoDB data volume
    
volumes:
  mongodb-data: {}