services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/songbook"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: songbook
    volumes:
      - mongodb-data:/app/db

volumes:
  mongodb-data: {}
