#!/bin/bash

# Regexp for grep to only choose some file extensions for formatting
exts="\.\(py\)$"

# The formatter to use
black_formatter=$(which black)

# Check availability of the formatters
if [[ -z "$black_formatter" ]]; then
    echo 1>&2 Black formatter "$black_formatter not found."
    echo 1>&2 "Please install Black first (see https://black.readthedocs.io/en/stable/getting_started.html)."
    exit 1
fi

# Format staged files
ISSUE_FOUND=false
for file in $(git diff --cached --name-only --diff-filter=ACMR | grep $exts); do
    if ! $black_formatter --check $file; then
        echo 1>&2 "Reformatting neeeded: $file"
        ISSUE_FOUND=true
    fi
done

if $ISSUE_FOUND; then
    echo 1>&2 "Please check formatting!"
    echo 1>&2 "-> commit canceled"
    echo 1>&2 ""
    exit 1
fi
