name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-dev.txt

      - name: Sort imports with isort
        run: |
          isort backend/src  # Sort imports with isort

      - name: Format code with Black
        run: |
          black backend/src  # Format the source code with Black

      - name: Run linting with Ruff
        run: |
          ruff backend/src  # Lint the source code with Ruff

      - name: Run tests with coverage
        run: |
          pytest --cov=backend/src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
